version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

#  app:
#    build: .
#    restart: always
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_DATABASE: mydb
#      DB_USERNAME: myuser
#      DB_PASSWORD: mypassword
#      JWT_SECRET: structo
#    ports:
#      - '3000:3000'
#    depends_on:
#      - db
